name: "OSMNames"

permalink: pretty

baseurl: ""

url: "https://www.osmnames.org"
plugins:
  - jekyll-sitemap

maps:
  key: BGkU8B3hfOMkm0UfV0rG

sass:
  style: :compressed
  sass_dir: styles/_sass

exclude:
- "styles/base.scss"
